# Numpy Array operations 

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2 : 7])
print("Slicing with step", arr[1 : 9 : 2])
print("Slicing with negative step", arr[-8])

Basic Slicing [3 4 5 6 7]
Slicing with step [2 4 6 8]
Slicing with negative step 3


# For 2d Array

In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Slicing 2D array", arr_2d[1, 2])
print('Entire row', arr_2d[1])
print("Entire column", arr_2d[:, 1])

Slicing 2D array 6
Entire row [4 5 6]
Entire column [2 5 8]


# Sorting

In [4]:
unsorted_arr = np.array([2, 3, 5, 7, 1, 23, 2, 5, 6])
print("Sorted array", np.sort(unsorted_arr))
print("Sorted 2d Array by columns", np.sort(arr_2d, axis=1))

arr_2d = np.array([[3, 1, 2],
                   [6, 5, 9],
                   [9, 8, 7]])
print("Sorted 2d Array by columns", np.sort(arr_2d, axis=0))
print("Sorted 2d Array by rows", np.sort(arr_2d, axis=1))

Sorted array [ 1  2  2  3  5  5  6  7 23]
Sorted 2d Array by columns [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sorted 2d Array by columns [[3 1 2]
 [6 5 7]
 [9 8 9]]
Sorted 2d Array by rows [[1 2 3]
 [5 6 9]
 [7 8 9]]


# Filter

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


# Filter With Mask

In [6]:
mask = numbers > 5
print("Numbers greater then 5:", numbers[mask]) 

Numbers greater then 5: [ 6  7  8  9 10]


# Fancy indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Indices of numbers greater than 5:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Indices of numbers greater than 5: [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers > 5, 'True', 'False')
print("Condition array:", condition_array)

Condition array: ['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


# Adding and Removing Data

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

combined_arr = np.concatenate((arr1, arr2))
print("Combined array (addition):", combined_arr)

Combined array (addition): [ 1  2  3  4  5 10 20 30 40 50]


# Array Compatibility

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
C = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape )

Comatibility chapes False


In [24]:
original = np.array([[1, 2], [5, 7]])
new_row = np.array([3, 4])

with_new_row = np.vstack((original, new_row)) 

print(original)
print()
print(with_new_row)

print()

#For horizontal stacking
new_col = np.array([[6], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [5 7]]

[[1 2]
 [5 7]
 [3 4]]

[[1 2 6]
 [5 7 8]]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
deleted_arr = np.delete(arr, 2)
print("Original array:", arr)
print("Array after deletion:", deleted_arr)

Original array: [1 2 3 4 5]
Array after deletion: [1 2 4 5]
