## Numpy Array and basics 
Learn about numpy

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_1d = np .array([1, 2, 3, 4, 5])
print("arr 1D:", arr_1d)


arr_2d = np .array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

arr 1D: [1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List Vs numpy Array

In [3]:
python_list = [1, 2, 3]
print("python list multiplication:", python_list * 2)


np_array = np.array([1, 2, 3])   #Element wise multiplication
print("numpy array multiplication:", np_array * 2)


import time

start = time.time()
python_list = [i * 2 for i in range(1000000)]
print("\n List operator time: ", time.time() - start)



start = time.time()
np_array = np.arange(1000000) * 2
print("\nNumpy operation time:", time.time() - start)

python list multiplication: [1, 2, 3, 1, 2, 3]
numpy array multiplication: [2 4 6]

 List operator time:  0.48508358001708984

Numpy operation time: 0.021770954132080078


### Creating Array From Scratch

In [4]:
zeros = np.zeros((4, 3))
print(zeros)

print()

ones = np.ones((2, 5))
print(ones)

print()

full = np.full((2, 2), 7)
print(full)

print()

random = np.random.random((3, 2))
print(random)

print()

sequence = np.arange(0, 10, 2)
print(sequence)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[7 7]
 [7 7]]

[[0.66193781 0.07105112]
 [0.08507225 0.02378752]
 [0.89826554 0.75605541]]

[0 2 4 6 8]


### Vector, Matrix and Tensor

In [13]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

print()

matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
print("Matrix:\n", matrix)

print()

tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print("Tensor:", tensor)

Vector: [1 2 3]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor: [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape of arr:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("size of arr:", arr.size)
print("Data type of arr:", arr.dtype)

Shape of arr: (2, 3)
Number of dimensions: 2
size of arr: 6
Data type of arr: int64


### Array resharing

In [22]:
arr = np.arange(12)
print("Original Array ", arr)

reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)


flattend = reshaped_arr.flatten()
print("Flattend array:", flattend)

#ravel() returns a flattened array, but it is a view of the original array whenever possible. This means that if you modify the raveled array, it may also modify the original array. In contrast, flatten() always returns a copy of the original array, so modifying the flattened array will not affect the original array.
raveled = reshaped_arr.ravel()
print("Raveled array:", raveled)

#Transpose
transposed = reshaped_arr.T
print("Transposed array:\n", transposed)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
