## Numpy Array and basics 
Learn about numpy

In [2]:
import numpy as np

### Creating array from list

In [8]:
arr_1d = np .array([1, 2, 3, 4, 5])
print("arr 1D:", arr_1d)


arr_2d = np .array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

arr 1D: [1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List Vs numpy Array

In [11]:
python_list = [1, 2, 3]
print("python list multiplication:", python_list * 2)


np_array = np.array([1, 2, 3])   #Element wise multiplication
print("numpy array multiplication:", np_array * 2)


import time

start = time.time()
python_list = [i * 2 for i in range(1000000)]
print("\n List operator time: ", time.time() - start)



start = time.time()
np_array = np.arange(1000000) * 2
print("\nNumpy operation time:", time.time() - start)

python list multiplication: [1, 2, 3, 1, 2, 3]
numpy array multiplication: [2 4 6]

 List operator time:  0.12993550300598145

Numpy operation time: 0.01284170150756836


### Creating Array From Scratch

In [24]:
zeros = np.zeros((4, 3))
print(zeros)

print()

ones = np.ones((2, 5))
print(ones)

print()

full = np.full((2, 2), 7)
print(full)

print()

random = np.random.random((3, 2))
print(random)

print()

sequence = np.arange(0, 10, 2)
print(sequence)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[7 7]
 [7 7]]

[[0.29240957 0.1469723 ]
 [0.16092303 0.52337215]
 [0.19943207 0.49270941]]

[0 2 4 6 8]
